[package]
name = "pathfinder_client"
version = "0.1.0"
authors = ["mgr_inz_rafal <rchabowski@gmail.com>"]

[dependencies]
pathfinder = { path = "../pathfinder" }
iron = "*"

[dependencies.bodyparser]
git = "https://github.com/iron/body-parser.git"